project:
  type: website

website:
  title: "Metagenomics Nanopore Workflow"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Inputs"
        file: inputs.qmd
      - text: "Pipeline"
        file: pipeline.qmd
      - text: "Results"
        file: results.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true